## Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

variables:
  tag: '$(Build.BuildId)'
  trivyVersion: 0.48.0

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      inputs:
#        containerRegistry: 'Docker-hub'
#        repository: 'anup1999/technofex'
#        command: 'buildAndPush'
#        Dockerfile: '**/Dockerfile'
#        tags: |
#          $(tag)
    - script: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
        sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
#        pwd
#        trivy -v
    - task: KubectlInstaller@0
      displayName: 'Install kubectl'
      inputs:
          versionSpec: 'v1.21.5'
    - task: DownloadSecureFile@1
      inputs:
        name: 'qa-cluster-az.yaml'
    - script: |
        export KUBECONFIG=~/.kube/config
        NAMESPACE="companyaccountms"
        PODS=$(kubectl --kubeconfig $KUBECONFIG get pods -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}')

        for POD in $PODS; do
            echo "Scanning pod: $POD"
            kubectl --kubeconfig $KUBECONFIG get pods $POD -n $NAMESPACE -o json | trivy k8s --kubeconfig $KUBECONFIG --report=summary pods
        done
      displayName: 'Run kubectl commands'
#    - task: CmdLine@2
#      displayName: 'Run Trivy Scan'
#      inputs:
#         script: |
#          trivy i --format template --template "@html.tpl" -o report.html anup1999/technofex:$(tag)
#    - task: publishhtmlreport@1
#      displayName: 'Published trivy scan report'
#      inputs:
#        htmlType: 'genericHTML'
#        htmlPath: '$(System.DefaultWorkingDirectory)/report.html'