## Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-hub'
        repository: 'anup1999/technofex'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-hub'
        command: 'login'
    - task: trivy@1
      inputs:
        image: 'anup1999/technofex:$(tag)'
        severities: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'